/* Marça saved storefront: one card per brand → country → MRU denomination → Bankily/WhatsApp. */
(function(){"use strict";
var itunes=window.MARCA_ITUNES,cfg=window.MARCA_CONFIG||{};
var psCards=[['Playstation USA PSN 10 USD',10,500],['PSN USA 25 USD',25,1250],['PSN USA 50 USD',50,2500],['PSN USA 75 USD',75,3750],['PSN USA 100 USD',100,5000],['PSN USA 150 USD',150,7500],['PSN USA 200 USD',200,10000],['PSN USA 250 USD',250,12500],['Playstation USD Open Range',25,1250,12500]], xboxLive=[['XBOX USA 5 USD',5,250],['Xbox USA 10 USD',10,500],['Xbox USA 20 USD',20,1000],['Xbox USA 25 USD',25,1250],['Xbox USA 50 USD',50,2500],['Xbox USA 100 USD',100,5000],['Xbox Game Pass Essential 12M',79.99,4000],['Xbox Game Pass Ultimate 1Month US',22.99,1150],['Xbox Game Pass Ultimate 3Months US',68.99,3450],['Xbox Game Pass Essential 1M',9.99,500],['Xbox Game Pass Essential 3M',24.99,1250],['Xbox Game Pass Essential 6M',39.99,2000],['Xbox USA 15 USD',15,750],['Xbox Live $60',60,3000],['Xbox Live $70',70,3500],['Xbox Live $75',75,3750],['Xbox Live $80',80,4000]], xboxPass=[['Xbox Game Pass Ultimate 1M',22.99,1150],['Xbox Game Pass Ultimate 3M',68.99,3450],['Xbox Game Pass Essential 1M',9.99,500],['Xbox Game Pass Essential 3M',24.99,1250],['Xbox Game Pass Essential 6M',39.99,2000],['Xbox Game Pass Essential 12M',79.99,4000]];
function cards(a){return a.map(function(x,i){return{id:'gift-'+i,denomLabel:x[0],priceMru:x[2],priceMruMax:x[3]||0}})}
var gifts=window.MARCA_GIFT_CARDS||{playstation:{markets:[{id:'us',region:'United States',regionAr:'الولايات المتحدة',productName:'PlayStation USD United States',cards:cards(psCards)}]},xbox:{markets:[{id:'us',region:'United States',regionAr:'الولايات المتحدة',productName:'Xbox Live / Game Pass USD United States',cards:cards(xboxLive.concat(xboxPass))}]}};

if(!itunes||!itunes.markets)return;
var products=[
{id:"itunes",title:"بطاقة آيتونز",en:"iTunes / Apple Gift Card",image:"assets/products/itunes.svg?v=21",alt:"شعار بطاقة آيتونز / iTunes",data:itunes},
{id:"playstation",title:"بطاقة PlayStation",en:"PlayStation Gift Card",image:"assets/products/playstation.svg?v=21",alt:"شعار بطاقة PlayStation",data:gifts.playstation},
{id:"xbox",title:"بطاقة Xbox",en:"Xbox Gift Card",image:"assets/products/xbox.svg?v=21",alt:"شعار بطاقة Xbox",data:gifts.xbox},
{id:"snapchat-plus",title:"سناب شات بلس",en:"Snapchat Plus",image:"assets/products/snapchat.svg?v=21",alt:"شعار سناب شات بلس",data:{markets:[{id:"plus",region:"Snapchat Plus",regionAr:"سنة واحدة",productName:"سناب شات بلس",cards:[{id:"1y",denomLabel:"سنة",priceMru:490}]}]}}
].filter(function(p){return p.data&&p.data.markets});
var state={product:null,market:null,card:null,step:"country"},grid=document.getElementById("product-grid"),search=document.getElementById("catalog-search"),flow=document.getElementById("itunes-block"),countryStep=document.getElementById("itunes-step-country"),denomStep=document.getElementById("itunes-step-denom"),paymentStep=document.getElementById("itunes-step-payment"),countryGrid=document.getElementById("itunes-country-grid"),denomGrid=document.getElementById("itunes-denom-grid"),selectedCountry=document.getElementById("itunes-selected-country"),selectedOrder=document.getElementById("itunes-selected-order"),check=document.getElementById("itunes-payment-check"),wa=document.getElementById("itunes-wa");
function digits(n){var s=String(Math.round(Number(n))),o="";for(var i=0;i<s.length;i++){if(i&&(s.length-i)%3===0)o+=",";o+=s.charAt(i)}return o}
function price(c){return c.priceMruMax?digits(c.priceMru)+"–"+digits(c.priceMruMax)+" أوقية (MRU)":digits(c.priceMru)+" أوقية (MRU)"}
function clear(n){while(n&&n.firstChild)n.removeChild(n.firstChild)}
function title(){return state.product?state.product.title:"البطاقة"}
function step(s){state.step=s;var x={country:countryStep,denom:denomStep,payment:paymentStep};Object.keys(x).forEach(function(k){if(x[k]){x[k].hidden=k!==s;x[k].classList.toggle("is-active",k===s)}});var h=document.getElementById("itunes-flow-title"),sub=document.getElementById("itunes-flow-sub");if(h)h.textContent=s==="country"?"اختر الدولة أو المنطقة":s==="denom"?"اختر الفئة":"إكمال الطلب";if(sub)sub.textContent=s==="country"?"اختر منطقة "+title()+".":s==="denom"?"الأسعار المعروضة بالأوقية الموريتانية (MRU) فقط.":"راجع التفاصيل ووافق على الدفع عبر بنكيلي، ثم أرسل طلبك عبر واتساب."}
function home(){state.product=state.market=state.card=null;if(flow)flow.hidden=true;step("country");if(check)check.checked=false;sync()}
function open(p){if(!flow)return;state.product=p;state.market=state.card=null;flow.hidden=false;var k=flow.querySelector(".itunes-flow-head .cat-kicker");if(k)k.textContent=p.title+" / "+p.en;step("country");countries();sync();flow.scrollIntoView({behavior:"smooth",block:"start"})}
function card(p){var b=document.createElement("button");b.type="button";b.id=p.id+"-product-card";b.className="product-card featured gift-product-card "+p.id+"-product-card";b.setAttribute("role","listitem");b.setAttribute("aria-label","اختر "+p.title+" — "+p.en);var i=document.createElement("div");i.className="product-icon product-icon-img gift-product-logo";var img=document.createElement("img");img.src=p.image;img.alt=p.alt;img.width=112;img.height=112;img.loading="lazy";img.decoding="async";i.appendChild(img);b.appendChild(i);var cat=document.createElement("span");cat.className="product-category";cat.textContent="بطاقات رقمية";b.appendChild(cat);var h=document.createElement("h3");h.className="product-title";h.textContent=p.title;b.appendChild(h);var en=document.createElement("p");en.className="product-name-en";en.textContent=p.en;b.appendChild(en);var d=document.createElement("p");d.className="product-desc";d.textContent="كل المناطق والفئات — السعر بالأوقية الموريتانية.";b.appendChild(d);var c=document.createElement("span");c.className="product-cta";c.textContent="اختيار المنطقة";b.appendChild(c);b.addEventListener("click",function(){open(p)});return b}
function wireSnapchatLogo(){
  if(!grid)return;
  var snap=grid.querySelector('[data-product-id="snapchat-plus"]');
  if(!snap)return;
  var img=snap.querySelector("img");
  if(img){img.src="assets/products/snapchat-plus.png?v=20";img.alt="Snapchat Plus";return}
  var icon=snap.querySelector(".product-icon");
  if(!icon)return;
  icon.textContent="";
  icon.classList.add("product-icon-img");
  img=document.createElement("img");
  img.src="assets/products/snapchat-plus.png?v=20";
  img.alt="Snapchat Plus";
  img.width=112;img.height=112;img.loading="lazy";img.decoding="async";
  icon.appendChild(img);
}
function render(){wireSnapchatLogo();products.forEach(function(p){if(grid&&!document.getElementById(p.id+"-product-card"))grid.appendChild(card(p))})}
function countries(){if(!countryGrid||!state.product)return;clear(countryGrid);var q=search?String(search.value||"").trim().toLowerCase():"";state.product.data.markets.forEach(function(m){if(q&&(m.region+" "+m.regionAr+" "+m.productName).toLowerCase().indexOf(q)<0)return;var b=document.createElement("button");b.type="button";b.className="itunes-country-card";b.setAttribute("role","listitem");b.setAttribute("aria-label","اختيار "+m.regionAr+" — "+m.region);var ar=document.createElement("strong"),en=document.createElement("span");ar.textContent=m.regionAr;en.textContent=m.region;b.appendChild(ar);b.appendChild(en);b.addEventListener("click",function(){country(m)});countryGrid.appendChild(b)});if(!countryGrid.firstChild){var e=document.createElement("p");e.className="itunes-empty";e.textContent="لا توجد منطقة مطابقة.";countryGrid.appendChild(e)}}
function country(m){state.market=m;state.card=null;if(selectedCountry)selectedCountry.textContent=m.regionAr+" — "+m.region;denoms();step("denom");if(flow)flow.scrollIntoView({behavior:"smooth",block:"start"})}
function denoms(){if(!denomGrid||!state.market)return;clear(denomGrid);if(!state.market.cards||!state.market.cards.length){var e=document.createElement("p");e.className="itunes-empty";e.textContent="لا توجد فئات منشورة حالياً لهذه المنطقة على Tokenstore.";denomGrid.appendChild(e);return}state.market.cards.forEach(function(c){var b=document.createElement("button");b.type="button";b.className="itunes-denom-card";b.setAttribute("role","listitem");b.setAttribute("aria-label",c.denomLabel+" — "+price(c));var d=document.createElement("strong"),p=document.createElement("span");d.textContent=c.denomLabel;p.textContent=price(c);b.appendChild(d);b.appendChild(p);b.addEventListener("click",function(){denom(c)});denomGrid.appendChild(b)})}
function denom(c){state.card=c;if(selectedOrder)selectedOrder.textContent=title()+" · "+state.market.regionAr+" · "+c.denomLabel+" · "+price(c);if(check)check.checked=false;sync();step("payment");if(flow)flow.scrollIntoView({behavior:"smooth",block:"start"})}
function url(){var phone=String(cfg.WHATSAPP_E164||"22248650585").replace(/\D/g,"");var l=["السلام عليكم،","أريد طلب "+title()+" من متجر Marça:","","• المنتج: "+title()+" ("+state.product.en+")","• المنطقة: "+state.market.regionAr+" ("+state.market.region+")","• الفئة: "+state.card.denomLabel,"• السعر: "+price(state.card),"• تأكيد الدفع: أوافق على الدفع فقط عبر بنكيلي (Bankily) ✓"];if(window.MarcaAffiliate&&window.MarcaAffiliate.getRef())l.push("• REF:"+window.MarcaAffiliate.getRef());l.push("","شكرًا لكم.");return"https://wa.me/"+phone+"?text="+encodeURIComponent(l.join("\n"))}
function sync(){if(!wa)return;var ok=!!(check&&check.checked&&state.product&&state.market&&state.card);wa.classList.toggle("is-disabled",!ok);wa.setAttribute("aria-disabled",ok?"false":"true");if(ok){wa.href=url();wa.removeAttribute("tabindex")}else{wa.removeAttribute("href");wa.setAttribute("tabindex","-1")}}
function init(){render();if(flow)flow.hidden=true;if(search)search.addEventListener("input",function(){if(state.step==="country"&&flow&&!flow.hidden)countries()});var bh=document.getElementById("itunes-back-home"),bc=document.getElementById("itunes-back-country"),bd=document.getElementById("itunes-back-denom"),bd2=document.getElementById("itunes-back-denom-2");if(bh)bh.addEventListener("click",home);if(bc)bc.addEventListener("click",function(){step("country");countries()});if(bd)bd.addEventListener("click",function(){step("denom")});if(bd2)bd2.addEventListener("click",function(){step("denom")});if(check)check.addEventListener("change",sync);if(wa)wa.addEventListener("click",function(e){if(wa.getAttribute("aria-disabled")==="true")e.preventDefault()})}if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",init);else init()})();